name: ESP32 Auto Flash

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  flash:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Flash ESP32 (force CMD)
        shell: cmd
        run: |
          echo Flashing ESP32...
          cd esp32-github-runner
          esp32_flash.bat
